# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "14:51"
      # Use Japan Standard Time (UTC +09:00)
      timezone: "Europe/London"
    target-branch: "dependabot-changes"  
