name: PR commits
on: pull_request
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        id: set_commit_messages
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
           COMMIT_MESSAGES= curl ${{ github.event.pull_request.commits_url }} | jq '[.[] | {message: .commit.message, name: .commit.committer.name, parents: [.parents[].html_url]}]'
           echo ::set-output name=commit_messages::${COMMIT_MESSAGES}
                - name: Create comment
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 66
          body: |
            ${{ steps.set_commit_messages.outputs.commit_messages }}
          reactions: 'rocket'
