name: PR commits
on: 
  pull_request:
  repository_dispatch:
    types: [commit_messages]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: set_commit_messages
        run: |
            content=$(curl -s  ${{ github.event.client_payload.pr_url }}) 
            COMMIT_MESSAGES=$( jq '.[] | .commit.message' <<< "${content}" )
            echo ::set-output name=commit_messages::${COMMIT_MESSAGES}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: | 
                   ${{ github.event.client_payload.pr_number }}
          body: |
            ${{ steps.set_commit_messages.outputs.commit_messages }}
          reactions: 'rocket'
