on: [pull_request,pull_request_review_comment,issue_comment]
    types: [created,deleted,edited]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: nellyk/task-list-pr-checker@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}