on:
  pull_request:
    types: [opened,edited]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}